LeagueofItemSets/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from database import urls as db_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(db_urls, namespace='lois'))
]

database/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^itemset$', views.item_set, name='itemset'),
    url(r'^json&id=([\w\d]+)$', views.json_string, name='json'),
    url(r'^download&id=([\w\d]+)$', views.download, name='download'),
    url(r'^([\w]+)/*$', views.item_select, name='items'),
    url(r'^$', views.index, name='index'),
]

database/models.py
from django.db import models
from django.utils import timezone


class PlayerItemSet(models.Model):
        ID = models.CharField(primary_key=True, max_length=50, default="0") #or other field
        Title = models.CharField(max_length=200, default="Made by LoIS")
        Date = models.DateTimeField('date created', default=timezone.now)
        Map = models.CharField(max_length=3, default="any")
        Mode = models.CharField(max_length=7, default="any")
        SortRank = models.SmallIntegerField(default=0)

        #to determine returned value
        def __str__(self):
                return str(self.ID)


class Block(models.Model):
        BlockType = models.CharField(max_length=200, default="Custom made")
        RecMath = models.CharField(max_length=10, default="false")
        MinSummonerLevel = models.SmallIntegerField(default=-1)
        MaxSummonerLevel = models.SmallIntegerField(default=-1)
        ShowIfSummonerSpell = models.CharField(max_length=50, default="")
        HideIfSummonerSpell = models.CharField(max_length=50, default="")
        PlayerItemSet = models.ForeignKey(PlayerItemSet)

        def __str_(self):
                return self.BlockType


class BlockItem(models.Model):
        ItemID = models.IntegerField(default=0)
        Count = models.IntegerField(default=1)
        Block = models.ForeignKey(Block)

        # to determine return value
        def __str__(self):
                return str(self.ItemID)


class Item(models.Model):
        ItemID = models.IntegerField(primary_key=True, default=0)
        Description = models.CharField(max_length=200, default="Describe me!")
        GoldTotal = models.SmallIntegerField(default=0)
        GoldBase = models.SmallIntegerField(default=0)
        Name = models.CharField(max_length=200, default="item_name")
        Tags = models.CharField(max_length=200, default=[""])
        Icon = models.CharField(max_length=200, default="http://ddragon.leagueoflegends.com/cdn/5.17.1/img/champion/1001.png")
        Stacks = models.IntegerField(default=1)
        Into = models.CharField(max_length=200, default=[""])
        From = models.CharField(max_length=200, default=[""])
        Purchasable = models.BooleanField(default=False)

        def get_stats(self):
            return self.itemstat.nonempty_stats()

        #to determine returned value
        def __str__(self):
                return self.Name


class ItemStat(models.Model):
        ItemID = models.OneToOneField(Item, primary_key=True)
        FlatArmorMod = models.FloatField(null=True, blank=True)
        FlatAttackSpeedMod = models.FloatField(null=True, blank=True)
        FlatBlockMod = models.FloatField(null=True, blank=True)
        FlatCritChanceMod = models.FloatField(null=True, blank=True)
        FlatCritDamageMod = models.FloatField(null=True, blank=True)
        FlatExpBonus = models.FloatField(null=True, blank=True)
        FlatEnergyPoolMod = models.FloatField(null=True, blank=True)
        FlatEnergyRegenMod = models.FloatField(null=True, blank=True)
        FlatHPPoolMod = models.FloatField(null=True, blank=True)
        FlatHPRegenMod = models.FloatField(null=True, blank=True)
        FlatMPPoolMod = models.FloatField(null=True, blank=True)
        FlatMPRegenMod = models.FloatField(null=True, blank=True)
        FlatMagicDamageMod = models.FloatField(null=True, blank=True)
        FlatMovementSpeedMod = models.FloatField(null=True, blank=True)
        FlatPhysicalDamageMod = models.FloatField(null=True, blank=True)
        FlatSpellBlockMod = models.FloatField(null=True, blank=True)
        PercentArmorMod = models.FloatField(null=True, blank=True)
        PercentAttackSpeedMod = models.FloatField(null=True, blank=True)
        PercentBlockMod = models.FloatField(null=True, blank=True)
        PercentCritChanceMod = models.FloatField(null=True, blank=True)
        PercentCritDamageMod = models.FloatField(null=True, blank=True)
        PercentDodgeMod = models.FloatField(null=True, blank=True)
        PercentExpBonus = models.FloatField(null=True, blank=True)
        PercentHPPoolMod = models.FloatField(null=True, blank=True)
        PercentHPRegenMod = models.FloatField(null=True, blank=True)
        PercentLifeStealMod = models.FloatField(null=True, blank=True)
        PercentMPPoolMod = models.FloatField(null=True, blank=True)
        PercentMPRegenMod = models.FloatField(null=True, blank=True)
        PercentMagicDamageMod = models.FloatField(null=True, blank=True)
        PercentMovementSpeedMod = models.FloatField(null=True, blank=True)
        PercentPhysicalDamageMod = models.FloatField(null=True, blank=True)
        PercentSpellBlockMod = models.FloatField(null=True, blank=True)
        PercentSpellVampMod = models.FloatField(null=True, blank=True)
        BaseHPRegenMod = models.FloatField(null=True, blank=True)
        BaseMPRegenMod = models.FloatField(null=True, blank=True)

        def nonempty_stats(self):
            stat_list = {}
            for field in self._meta.get_fields():
                if (field.name is "ItemID"):
                    continue
                value = getattr(self, field.name)
                if (value is not None):
                    stat_list[field.name] = value
            return stat_list

        #to determine returned value
        def __str__(self):
                return str(self.ItemID)


class Champion(models.Model):
        ChampID = models.IntegerField(primary_key=True, default=0)
        Name = models.CharField(max_length=200, default="All")
        Key = models.CharField(max_length=200, default="All")
        Icon = models.CharField(max_length=200, default="http://ddragon.leagueoflegends.com/cdn/5.17.1/img/champion/Teemo.png")
        Tags = models.CharField(max_length=200, default="");

        #to determine returned value
        def __str__(self):
                return self.Name


class ChampionStat(models.Model):
        ChampID = models.OneToOneField(Champion, primary_key=True)
        Armor = models.FloatField(null=True, blank=True)
        ArmorPerLevel = models.FloatField(null=True, blank=True)
        AttackDamage = models.FloatField(null=True, blank=True)
        AttackDamagePerLevel = models.FloatField(null=True, blank=True)
        AttackRange = models.FloatField(null=True, blank=True)
        AttackSpeedOffset = models.FloatField(null=True, blank=True)
        AttackSpeedPerLevel = models.FloatField(null=True, blank=True)
        Crit = models.FloatField(null=True, blank=True)
        CritPerLevel = models.FloatField(null=True, blank=True)
        HP = models.FloatField(null=True, blank=True)
        HPPerLevel = models.FloatField(null=True, blank=True)
        HPRegen = models.FloatField(null=True, blank=True)
        HPRegenPerLevel = models.FloatField(null=True, blank=True)
        MoveSpeed = models.FloatField(null=True, blank=True)
        MP = models.FloatField(null=True, blank=True)
        MPPerLevel = models.FloatField(null=True, blank=True)
        MPRegen = models.FloatField(null=True, blank=True)
        MPRegenPerLevel = models.FloatField(null=True, blank=True)
        SpellBlock = models.FloatField(null=True, blank=True)
        SpellBlockPerLevel = models.FloatField(null=True, blank=True)

        #to determine returned value
        def __str__(self):
                return str(self.ChampID)


class Version(models.Model):
        Region = models.CharField(primary_key=True, max_length=10, default="eune")
        Version = models.CharField(max_length=20, default="1.0.0")

        #to determine returned value
        def __str__(self):
                return self.Version

database/views.py
import os.path as path
import json
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from .models import Champion, ChampionStat, Item, ItemStat
from .scripts.convert import item_set_manager as ism, block_manager as bm, block_item_manager as bim
from .scripts.convert import create_json_from_db as json_db

def index(request):
	champ_list = Champion.objects.all()
	context = {'champ_list': champ_list}
	return render(request, 'database/index.html', context)

def item_select(request, champ_key):
	if (champ_key == "All"):
		champ_stats = "[{'MPRegen': 0, 'SpellBlock': 0, 'Crit': 0, 'AttackDamage': 0, \
						'MP': 0, 'HPRegen': 0, 'HP': 0, 'Armor': 0, 'MoveSpeed': 0, \
						'AttackSpeedOffset': 0}]"
		champion = {"Name": "All", "Icon": path.join(settings.STATIC_URL,"Unknown.png")}
	else:
		champion = get_object_or_404(Champion, Key = champ_key)
		champ_stats = ChampionStat.objects.filter(pk = champion.ChampID).values()
	items = Item.objects.all()

	context = {
		"champ": champion,
		"champ_stats": champ_stats,
		"item_list": items
	}
	return render(request, 'database/items.html', context)

@csrf_exempt
def item_set(request):
	item_set = request.POST.get("item_set", "")
	item_set_json = json.loads(item_set)
	ism_id = ism(is_title = item_set_json["name"], is_map = item_set_json["map"], new_entry = True)

	for block in item_set_json["blocks"]:
		bm_id = bm(ism_id, name = block["name"], rec_math = block["recmath"], new_entry = True)
		for item in block["items"]:
			bim(item, bm_id, count = block["items"][item],new_entry = True)
	context = {"item_set_id": ism_id}
	return render(request, 'database/item_set.html', context)

def json_string(request, ism_id):
	json_string = json_db(ism_id)
	context = {"json": json_string}
	return render(request, 'database/view_json.html', context)

# Method for sending files to users
def download(request, ism_id):
	json_string = json_db(ism_id)
	response = HttpResponse(json_string, content_type ='application/json')
	response["Content-Disposition"] = 'attachment; filename="' + ism_id + '.json"'
	return response

database/templates/database/index.html
<html>
<head>
{% load staticfiles %}
<meta charset="UTF-8" />
<!-- ensures proper scaling on mobile devices -->
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/index_style.css' %}" />
<link href='http://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
<!-- <script src="{% static 'javascript/common_script.js' %}" defer></script> -->
<script src="{% static 'javascript/index_script.js' %}" defer></script>
<title>League of Item Sets</title>
</head>
<body>
  <div class="text">
    <h1> Welcome to League of Item Sets!</h1>
    <p> Here you can make your own item sets, download them and use them in-game!</p>
    <p> To begin choose one of the champions or click all.</p>
  </div>
  <br />
  <div class="champions">
    <span class="big-text" id="all-text"><a href="{% url 'lois:items' "All" %}">All</a></span>
    <div class="filter" id="filter-div">
      <span>Filter by name or tag</span>
      <input type="text" id="filter-champs" title="Filter champions"/>
    </div>
    <div id="champ-icons-div">
      {% if champ_list %}
        {% for champion in champ_list %}
          <a href="{% url 'lois:items' champion.Key %}" ><img src="{{champion.Icon}}"
                title="{{champion.Name}}" alt="{{champion.Name}}" data-tags="{{champion.Tags}}" class="icons" /></a>
        {% endfor %}
      {% else %}
        <p class="big-text"> Could not display champions!</p>
      {% endif %}
    </div>
  </div>
  <div class="footer">
    <p>League of Item Sets isn’t endorsed by Riot Games and doesn’t reflect the views or opinions of
      Riot Games or anyone officially involved in producing or managing League of Legends.
      League of Legends and Riot Games are trademarks or registered trademarks of Riot Games, Inc.
      League of Legends © Riot Games, Inc.</p>
  </div>
</body>
</html>

database/templates/database/item_set.html
<!DOCTYPE html>
<html>
<head>
{% load staticfiles %}
<meta charset="UTF-8" />
<!-- ensures proper scaling on mobile devices -->
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'css/itemset_style.css' %}" rel="stylesheet" type="text/css"/>
<!-- import below is for the awesome font -->
<link href='http://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
<title>LeagueofItemSets</title>
</head>
<body>
<div class="content">
	<h1>Congratulations!</h1>
	<p>You have succesfully created an item set! <br />
		To use the item set, you need to download it by clicking on the Download JSON button	below	and put it in your
		<br /> <br /><b>Riot Games\League of Legends\Config\Global\Recommended\</b> <br /><br />
		folder to use it on any champion or
		<br /> <br /><b>Riot Games\League of Legends\Config\Champions\{CHAMPION}\Recommended\</b> <br/> <br />
		folder to use it on a specific champion.</p>
	<p>You can view the JSON yourself by clicking the View JSON button or opening the downloaded file in any text editor.</p> <br />
	<form action="{% url 'lois:download' item_set_id %}">
		<button type="submit" id="download-json" class="button">Download JSON</button>
	</form>
	<form action="{% url 'lois:json' item_set_id %}">
		<button type="submit" id="view-json" class="button">View JSON</button>
	</form>
</div>
<div class="footer">
  <p>League of Item Sets isn’t endorsed by Riot Games and doesn’t reflect the views
     or opinions of Riot Games or anyone officially involved in producing or managing
     League of Legends. League of Legends and Riot Games are trademarks or registered
     trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc.</p>
</div>
</body>
</html>

database/templates/database/items.html
<!DOCTYPE html>
<html>
<head>
{% load staticfiles %}
<meta charset="UTF-8" />
<!-- ensures proper scaling on mobile devices -->
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="stylesheet" type="text/css" href="{% static 'css/items_style.css' %}" defer/>
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" defer/>
<script src="{% static 'javascript/common_script.js' %}" defer></script>
<script src="{% static 'javascript/item_script.js' %}" defer></script>
<!-- import below is for the awesome font -->
<link href='http://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
<title>League of Item Sets</title>
</head>
<body>
<div class="head">
  <section class="left-side">
    <div class="icon">
      <p> {{champ.Name}} </p>
      <img id="champ-icon" src="{{champ.Icon}}" alt="{{champ.Name}}" height="80" title="{{champ.Name}}" />
    </div>
    <div id="stats-table-div" data-stats="{{champ_stats}}"></div>
  </section>
  <section class="right-side">
    <div class="buttons-container">
      <button type="button" id="build" data-url="{% url 'lois:itemset' %}" class="buttons"
              title="If you want you can download the item set as a JSON file">Done</button>
      <button type="button" id="add" class="buttons"
              title="Add a new block, which is a section of items in-game">Create new block</button>
      <button type="button" id="remove" class="buttons"
              title="Remove the selected block">Remove block</button>
      <select class="buttons" id="map-selector" title="Choose which maps you want the item set to appear on">
        <option value="any">Any map</option>
        <option value="SR">Summoner's Rift</option>
        <option value="HA">Howling Abyss</option>
        <option value="TT">Twisted Treeline</option>
        <option value="CS">Crystal Scar</option>
      </select>
      <select class="buttons" id="block-selector"
            title="Choose which block you want to add items to"></select>
    </div>
    <input type="text" id="item-set-name" value="Item set name"
            title="Edit this to set your item set name as it appears in-game" />
  <div id="blocks"></div>
</div>
<div class="toggle-items">
  <button type="button" id="items-button" class="hide-buttons" title="Toggle items">V</button>
</div>
<div class="items-div" id="items-div">
    <ul class="filter-buttons" id="filter-buttons-div">
      <li class="filter-button" id="filter-all">All</li>
      <li class="filter-button" id="filter-attack">Attack Damage</li>
      <li class="filter-button" id="filter-armor">Armor</li>
      <li class="filter-button" id="filter-health">Health</li>
      <li class="filter-button" id="filter-mana">Mana</li>
      <li class="filter-button" id="filter-consumable">Consumable</li>
      <li class="filter-button" id="filter-boots">Boots</li>
      <li class="filter-button" id="filter-nonboots">Nonboots Movement</li>
    </ul>
  <div class="filter" id="filter-div">
    <span>Filter items</span>
    <input type="text" id="filter-items" title="Filter items"></input>
  </div>
  <div class="item-info">
    <!-- <span>Item Info</span> -->
    <p id="item-info-name"></p>
    <p id="item-info-icon"></p>
    <p id="item-info-description"></p>
    <!-- <p>Stats</p> -->
    <p id="item-info-stats"></p>
  </div>
  <div class="item-icons" id="item-icons-div">
    {% for item in item_list %}
      {% if item.Purchasable == True %}
        <div class="item-icon" id="item-icon">
          <img src="{{item.Icon}}" alt="{{item.Name}}" title="{{item.Name}}"
              data-icon="{{item.Icon}}" id="item-{{item.ItemID}}" data-tags="{{item.Tags}}"
              data-stats="{{item.get_stats}}" data-into="{{item.Into}}" data-description="{{item.Description}}"
              data-cost="{{item.GoldBase}}" data-from="{{item.From}}"/>
          <span>{{item.GoldBase}}</span>
        </div>
      {% endif %}
    {% empty %}
        <p> Could not display items! </p>
    {% endfor %}
  </div>
  <div class="item-builds hide">
    <span>Builds into</span>
    <p id="item-builds-into-field"></p>
  </div>
  <div class="item-builds hide">
    <span>Builds from</span>
    <p id="item-builds-from-field"></p>
  </div>
</div>
<div class="footer">
  <p>League of Item Sets isn’t endorsed by Riot Games and doesn’t reflect the views
     or opinions of Riot Games or anyone officially involved in producing or managing
     League of Legends. League of Legends and Riot Games are trademarks or registered
     trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc.</p>
</div>
</body>
</html>

database/templates/database/view_json.html
<!DOCTYPE html>
<html>
<head>
{% load staticfiles %}
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<!-- ensures proper scaling on mobile devices -->
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'css/json_style.css' %}" rel="stylesheet" type="text/css" />
<script src="{% static 'javascript/json_script.js' %}" defer></script>
<!-- import below is for the awesome font -->
<link href='http://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
<title>LeagueofItemSets</title>
</head>
<body>
<div class="json">
  <p id="beautiful-json" data-json="{{json}}">Hello</p>
</div>
<div class="footer">
  <p>League of Item Sets isn’t endorsed by Riot Games and doesn’t reflect the views
     or opinions of Riot Games or anyone officially involved in producing or managing
     League of Legends. League of Legends and Riot Games are trademarks or registered
     trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc.</p>
</div>
</body>
</html>